version: "3.9"

services:
  tgaccupload:
    image: ghcr.io/JMAccorsi/tgaccupload:main
    container_name: tgaccupload
    environment:
      - CONFIG_FILE_URL=${CONFIG_FILE_URL}
    ports:
      - 8080:8080
    restart: unless-stopped